[package]
name = "git-pr"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
regex-lite = "0.1"

[dependencies.clap]
version = "4.5"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.ureq]
version = "3.0"
features = ["json"]
